apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 12
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 60
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 60
            periodSeconds: 1
