apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: key-pair
          secret:
            secretName: {{ .Chart.Name }}
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - '-c'
            - |
              echo -e "Checking for the availability of MySQL Server deployment";
              while ! nc -z {{ .Values.mysql.fullnameOverride }}-headless 3306;
                do sleep 1;
                printf "-";
              done;
              echo -e "  >> MySQL DB Server has started";
      containers:
        - name: {{ .Chart.Name }}
          image: {{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.fullnameOverride }}
                  key: mysql-root-password
          volumeMounts:
            - mountPath: {{ .Values.security.keyPairDir }}
              name: key-pair
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 12
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 60
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.server.port }}
            failureThreshold: 60
            periodSeconds: 1
