spring:
  datasource:
    url: jdbc:h2:mem:sirenorder
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


security:
  keypair:
    generateIfNotExist: true
