apiVersion: v2
name: api-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: mysql
    version: 9.23.0
    repository: https://charts.bitnami.com/bitnami
