replicaCount: 1

server:
  port: 8080

image:
  repository: null
  tag: null

service:
  type: LoadBalancer
  port: 8080

mysql:
  fullnameOverride: api-server-mysql
  auth:
    rootPassword: password
    database: sirenorder
