replicaCount: 1

server:
  port: 8080

image:
  repository: null
  tag: null

service:
  type: LoadBalancer
  port: 8080

mysql:
  fullnameOverride: api-server-mysql
  auth:
    rootPassword: password
    database: sirenorder

grafana:
  testFramework:
    enabled: false
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: password
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://api-server-prometheus-server
