server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
